### ISSUE TITLE
使用cocoscreator新建的lua工程运行无效果

### ISSUE THREAD

**Issue by Jian0326** [cocos-creator/creator-lua#2]
按照上面的文档一步一步建的项目过程都没有问题，但是无法出现效果，请问是需要其他什么操作的吗？
PS F:\creatore\testCreatore> .\convert-creator-build.bat F:\creatore\tes
F:\creatore\testCreatore\
BUILD_DIR=F:\creatore\testCreatore\build\lua
[Reader] jsfileSettings = F:\creatore\testCreatore\build\lua/src/setting
[OK] write file F:\creatore\testCreatore\src\imports\scenes.lua
[OK] write file F:\creatore\testCreatore\src\imports\assets.lua
[OK] write file F:\creatore\testCreatore\src\imports\files.lua
[OK] write file F:\creatore\testCreatore\src\imports\prefabs.lua
done.这些运行都是成功的，
不知道是否少了写操作，还有项目中并没有scene可以运行需要如何把scene弄过去啦

**Comment by xiang-xx** [comment]
我也是。 黑屏，创建的场景没有显示出来。
场景很简单，只在原来默认场景上加了个lable。

可能是由于什么原因导致的呀？

**Comment by dualface** [comment]
修改场景后要保存，然后再构建。
